
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author honli
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();

        utils = new myUtils();

        //add all blank frame into vec
        this.vecFrameProperty = new Vector();
        this.vecFrameProperty.addElement(new myFrameProperty("frame1", utils.myTYPE.ANALOG, false, "", utils.iconPathWhite, this.frame1, true));
        this.vecFrameProperty.addElement(new myFrameProperty("frame2", utils.myTYPE.ANALOG_DIGITAL, false, "", utils.iconPathWhite, this.frame2, true));
        this.vecFrameProperty.addElement(new myFrameProperty("frame3", utils.myTYPE.ANALOG, false, "", utils.iconPathWhite, this.frame3, true));
        this.vecFrameProperty.addElement(new myFrameProperty("frame4", utils.myTYPE.INVALID, false, "", utils.iconPathGrey, this.frame4, false));
        this.vecFrameProperty.addElement(new myFrameProperty("frame5", utils.myTYPE.ANALOG, false, "", utils.iconPathWhite, this.frame5, true));
        this.vecFrameProperty.addElement(new myFrameProperty("frame6", utils.myTYPE.DIGITAL, false, "", utils.iconPathWhite, this.frame6, true));
        this.vecFrameProperty.addElement(new myFrameProperty("frame7", utils.myTYPE.DIGITAL, false, "", utils.iconPathWhite, this.frame7, true));
        this.vecFrameProperty.addElement(new myFrameProperty("frame8", utils.myTYPE.DIGITAL, false, "", utils.iconPathWhite, this.frame8, true));
        this.vecFrameProperty.addElement(new myFrameProperty("frame9", utils.myTYPE.PWM, false, "", utils.iconPathWhite, this.frame9, true));
        this.vecFrameProperty.addElement(new myFrameProperty("frame10", utils.myTYPE.INVALID, false, "", utils.iconPathGrey, this.frame10, false));

        this.vecDeviceProperty = new Vector();
        this.vecDeviceProperty.addElement(new myDeviceProperty("LIGHT", utils.myTYPE.ANALOG, utils.iconPathLight, utils.iconPathLightFrame, this.jLabelLight, 2));
        this.vecDeviceProperty.addElement(new myDeviceProperty("BUZZER", utils.myTYPE.ANALOG, utils.iconPathBuzzer, utils.iconPathBuzzerFrame, this.jLabelBuzzer, 1));
        this.vecDeviceProperty.addElement(new myDeviceProperty("NOISE", utils.myTYPE.ANALOG, utils.iconPathNoise, utils.iconPathNoiseFrame, this.jLabelNoise, 1));
        this.vecDeviceProperty.addElement(new myDeviceProperty("RGB", utils.myTYPE.DIGITAL, utils.iconPathRgb, utils.iconPathRgbFrame, this.jLabelRGB, 1));
        this.vecDeviceProperty.addElement(new myDeviceProperty("BAR", utils.myTYPE.DIGITAL, utils.iconPathBar, utils.iconPathBarFrame, this.jLabelBar, 1));
        this.vecDeviceProperty.addElement(new myDeviceProperty("SERVO", utils.myTYPE.PWM, utils.iconPathServo, utils.iconPathServoFrame, this.jLabelServo, 1));
        
        this.jLabelLight.setName("LIGHT");
        this.jLabelBar.setName("BAR");
        this.jLabelBuzzer.setName("BUZZER");
        this.jLabelNoise.setName("NOISE");
        this.jLabelRGB.setName("RGB");
        this.jLabelServo.setName("SERVO");
        
        for (int i = 0; i < vecDeviceProperty.size(); i++){
            myDeviceProperty entity = (myDeviceProperty) vecDeviceProperty.get(i);
            entity.labelEntity.setText(entity.labelEntity.getName() + " X " + entity.validNum );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabelBar = new javax.swing.JLabel();
        jLabelNoise = new javax.swing.JLabel();
        jLabelMainBoard = new javax.swing.JLabel();
        frame1 = new javax.swing.JLabel();
        frame2 = new javax.swing.JLabel();
        frame4 = new javax.swing.JLabel();
        frame3 = new javax.swing.JLabel();
        frame7 = new javax.swing.JLabel();
        frame8 = new javax.swing.JLabel();
        frame9 = new javax.swing.JLabel();
        frame10 = new javax.swing.JLabel();
        frame5 = new javax.swing.JLabel();
        frame6 = new javax.swing.JLabel();
        jLabelLight = new javax.swing.JLabel();
        jLabelBuzzer = new javax.swing.JLabel();
        jLabelRGB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelServo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BAR.imageset/BAR_small.jpg"))); // NOI18N
        jLabelBar.setText("BAR");
        jLabelBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelBarMouseDragged(evt);
            }
        });
        jLabelBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelBarMouseReleased(evt);
            }
        });
        jLayeredPane1.add(jLabelBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 310, 190, -1));

        jLabelNoise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/LD.imageset/LD_small.png"))); // NOI18N
        jLabelNoise.setText("NOISE");
        jLabelNoise.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelNoiseMouseDragged(evt);
            }
        });
        jLabelNoise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelNoiseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelNoiseMouseReleased(evt);
            }
        });
        jLayeredPane1.add(jLabelNoise, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 174, 190, -1));

        jLabelMainBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/MB.imageset/MB_small.png"))); // NOI18N
        jLayeredPane1.add(jLabelMainBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 146, -1, -1));

        frame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/white.imageset/white.png"))); // NOI18N
        frame1.setToolTipText("");
        frame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frame1MouseClicked(evt);
            }
        });
        jLayeredPane1.add(frame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 17, -1, -1));

        frame2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/white.imageset/white.png"))); // NOI18N
        frame2.setToolTipText("");
        frame2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frame2MouseClicked(evt);
            }
        });
        jLayeredPane1.add(frame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 17, -1, -1));

        frame4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/gray.imageset/grey.png"))); // NOI18N
        jLayeredPane1.add(frame4, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 17, -1, -1));

        frame3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/white.imageset/white.png"))); // NOI18N
        frame3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frame3MouseClicked(evt);
            }
        });
        jLayeredPane1.add(frame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 17, -1, -1));

        frame7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/white.imageset/white.png"))); // NOI18N
        frame7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frame7MouseClicked(evt);
            }
        });
        jLayeredPane1.add(frame7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 368, -1, -1));

        frame8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/white.imageset/white.png"))); // NOI18N
        frame8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frame8MouseClicked(evt);
            }
        });
        jLayeredPane1.add(frame8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 368, -1, -1));

        frame9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/white.imageset/white.png"))); // NOI18N
        frame9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frame9MouseClicked(evt);
            }
        });
        jLayeredPane1.add(frame9, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 368, -1, -1));

        frame10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/gray.imageset/grey.png"))); // NOI18N
        jLayeredPane1.add(frame10, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 368, -1, -1));

        frame5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/white.imageset/white.png"))); // NOI18N
        frame5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frame5MouseClicked(evt);
            }
        });
        jLayeredPane1.add(frame5, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 132, -1, -1));

        frame6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/white.imageset/white.png"))); // NOI18N
        frame6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frame6MouseClicked(evt);
            }
        });
        jLayeredPane1.add(frame6, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 266, -1, -1));

        jLabelLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/LS.imageset/LS_small.jpg"))); // NOI18N
        jLabelLight.setText("LIGHT");
        jLabelLight.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelLightMouseDragged(evt);
            }
        });
        jLabelLight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelLightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelLightMouseReleased(evt);
            }
        });
        jLayeredPane1.add(jLabelLight, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 38, 180, -1));

        jLabelBuzzer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buzzer.imageset/buzzer_small.jpg"))); // NOI18N
        jLabelBuzzer.setText("BUZZER");
        jLabelBuzzer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelBuzzerMouseDragged(evt);
            }
        });
        jLabelBuzzer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBuzzerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelBuzzerMouseReleased(evt);
            }
        });
        jLayeredPane1.add(jLabelBuzzer, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 106, 190, -1));

        jLabelRGB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/RGB.imageset/RGB_small.jpg"))); // NOI18N
        jLabelRGB.setText("RGB");
        jLabelRGB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelRGBMouseDragged(evt);
            }
        });
        jLabelRGB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRGBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelRGBMouseReleased(evt);
            }
        });
        jLayeredPane1.add(jLabelRGB, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 242, 190, -1));

        jLabel2.setText("ANALOG");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 20));

        jLabel3.setText("ANALOG");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, 20));

        jLabel4.setText("ANALOG");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, 20));

        jLabel5.setText("DIGITAL");
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 20));

        jLabel1.setText("ANALOG/DIGITAL");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, 20));

        jLabelServo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/servo.imageset/micro servo_small.png"))); // NOI18N
        jLabelServo.setText("SERVO");
        jLabelServo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelServoMouseDragged(evt);
            }
        });
        jLabelServo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelServoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelServoMouseReleased(evt);
            }
        });
        jLayeredPane1.add(jLabelServo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, -1));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setText("DIGITAL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, 20));

        jLabel7.setText("DIGITAL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, 20));

        jLabel8.setText("PWM");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, 20));

        jTabbedPane1.addTab("Design", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab2", jPanel2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelNoiseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNoiseMouseDragged
        // TODO add your handling code here:
        Cursor cur = new Cursor(MOVE_CURSOR);
        this.setCursor(cur);
    }//GEN-LAST:event_jLabelNoiseMouseDragged

    private void jLabelNoiseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNoiseMouseReleased
        // TODO add your handling code here:
        Cursor cur = new Cursor(DEFAULT_CURSOR);
        this.setCursor(cur);

        this.utils.DragDownOperation(evt.getLocationOnScreen(), vecFrameProperty, this.jLabelNoise, vecDeviceProperty);
    }//GEN-LAST:event_jLabelNoiseMouseReleased

    private void jLabelLightMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLightMouseDragged
        // TODO add your handling code here:
        Cursor cur = new Cursor(MOVE_CURSOR);
        this.setCursor(cur);
    }//GEN-LAST:event_jLabelLightMouseDragged

    private void jLabelLightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLightMouseReleased
        // TODO add your handling code here:
        Cursor cur = new Cursor(DEFAULT_CURSOR);
        this.setCursor(cur);

        this.utils.DragDownOperation(evt.getLocationOnScreen(), vecFrameProperty, this.jLabelLight, vecDeviceProperty);
    }//GEN-LAST:event_jLabelLightMouseReleased

    private void jLabelBuzzerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuzzerMouseDragged
        // TODO add your handling code here:
        Cursor cur = new Cursor(MOVE_CURSOR);
        this.setCursor(cur);
    }//GEN-LAST:event_jLabelBuzzerMouseDragged

    private void jLabelRGBMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRGBMouseDragged
        // TODO add your handling code here:
        Cursor cur = new Cursor(MOVE_CURSOR);
        this.setCursor(cur);
    }//GEN-LAST:event_jLabelRGBMouseDragged

    private void jLabelBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBarMouseDragged
        // TODO add your handling code here:
        Cursor cur = new Cursor(MOVE_CURSOR);
        this.setCursor(cur);
    }//GEN-LAST:event_jLabelBarMouseDragged

    private void jLabelBuzzerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuzzerMouseReleased
        // TODO add your handling code here:
        Cursor cur = new Cursor(DEFAULT_CURSOR);
        this.setCursor(cur);

        this.utils.DragDownOperation(evt.getLocationOnScreen(), vecFrameProperty, this.jLabelBuzzer, vecDeviceProperty);
    }//GEN-LAST:event_jLabelBuzzerMouseReleased

    private void jLabelRGBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRGBMouseReleased
        // TODO add your handling code here:
        Cursor cur = new Cursor(DEFAULT_CURSOR);
        this.setCursor(cur);

        this.utils.DragDownOperation(evt.getLocationOnScreen(), vecFrameProperty, this.jLabelRGB, vecDeviceProperty);
    }//GEN-LAST:event_jLabelRGBMouseReleased

    private void jLabelBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBarMouseReleased
        // TODO add your handling code here:
        Cursor cur = new Cursor(DEFAULT_CURSOR);
        this.setCursor(cur);

        this.utils.DragDownOperation(evt.getLocationOnScreen(), vecFrameProperty, this.jLabelBar, vecDeviceProperty);
    }//GEN-LAST:event_jLabelBarMouseReleased

    private void jLabelNoiseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNoiseMousePressed
        // TODO add your handling code here:
        this.utils.DeviceLabelPressed(vecFrameProperty, this.jLabelNoise, vecDeviceProperty);
    }//GEN-LAST:event_jLabelNoiseMousePressed

    private void frame1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame1MouseClicked
        // TODO add your handling code here:
        utils.FramePopupMenu(frame1, vecFrameProperty, vecDeviceProperty, evt);
    }//GEN-LAST:event_frame1MouseClicked

    private void jLabelLightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLightMousePressed
        // TODO add your handling code here:
        this.utils.DeviceLabelPressed(vecFrameProperty, this.jLabelLight, vecDeviceProperty);
    }//GEN-LAST:event_jLabelLightMousePressed

    private void jLabelBuzzerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBuzzerMousePressed
        // TODO add your handling code here:
        this.utils.DeviceLabelPressed(vecFrameProperty, this.jLabelBuzzer, vecDeviceProperty);
    }//GEN-LAST:event_jLabelBuzzerMousePressed

    private void jLabelRGBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRGBMousePressed
        // TODO add your handling code here:
        this.utils.DeviceLabelPressed(vecFrameProperty, this.jLabelRGB, vecDeviceProperty);
    }//GEN-LAST:event_jLabelRGBMousePressed

    private void jLabelBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBarMousePressed
        // TODO add your handling code here:
        this.utils.DeviceLabelPressed(vecFrameProperty, this.jLabelBar, vecDeviceProperty);
    }//GEN-LAST:event_jLabelBarMousePressed

    private void frame2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame2MouseClicked
        // TODO add your handling code here:
        utils.FramePopupMenu(frame2, vecFrameProperty, vecDeviceProperty, evt);
    }//GEN-LAST:event_frame2MouseClicked

    private void frame3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame3MouseClicked
        // TODO add your handling code here:
        utils.FramePopupMenu(frame3, vecFrameProperty, vecDeviceProperty, evt);
    }//GEN-LAST:event_frame3MouseClicked

    private void frame5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame5MouseClicked
        // TODO add your handling code here:
        utils.FramePopupMenu(frame5, vecFrameProperty, vecDeviceProperty, evt);
    }//GEN-LAST:event_frame5MouseClicked

    private void frame6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame6MouseClicked
        // TODO add your handling code here:
        utils.FramePopupMenu(frame6, vecFrameProperty, vecDeviceProperty, evt);
    }//GEN-LAST:event_frame6MouseClicked

    private void frame7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame7MouseClicked
        // TODO add your handling code here:
        utils.FramePopupMenu(frame7, vecFrameProperty, vecDeviceProperty, evt);
    }//GEN-LAST:event_frame7MouseClicked

    private void frame8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame8MouseClicked
        // TODO add your handling code here:
        utils.FramePopupMenu(frame8, vecFrameProperty, vecDeviceProperty, evt);
    }//GEN-LAST:event_frame8MouseClicked

    private void frame9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frame9MouseClicked
        // TODO add your handling code here:
        utils.FramePopupMenu(frame9, vecFrameProperty, vecDeviceProperty, evt);
    }//GEN-LAST:event_frame9MouseClicked

    private void jLabelServoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelServoMouseDragged
        // TODO add your handling code here:
        Cursor cur = new Cursor(MOVE_CURSOR);
        this.setCursor(cur);
    }//GEN-LAST:event_jLabelServoMouseDragged

    private void jLabelServoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelServoMousePressed
        // TODO add your handling code here:
        this.utils.DeviceLabelPressed(vecFrameProperty, this.jLabelServo, vecDeviceProperty);
    }//GEN-LAST:event_jLabelServoMousePressed

    private void jLabelServoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelServoMouseReleased
        // TODO add your handling code here:
        Cursor cur = new Cursor(DEFAULT_CURSOR);
        this.setCursor(cur);

        this.utils.DragDownOperation(evt.getLocationOnScreen(), vecFrameProperty, this.jLabelServo, vecDeviceProperty);
    }//GEN-LAST:event_jLabelServoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel frame1;
    private javax.swing.JLabel frame10;
    private javax.swing.JLabel frame2;
    private javax.swing.JLabel frame3;
    private javax.swing.JLabel frame4;
    private javax.swing.JLabel frame5;
    private javax.swing.JLabel frame6;
    private javax.swing.JLabel frame7;
    private javax.swing.JLabel frame8;
    private javax.swing.JLabel frame9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBar;
    private javax.swing.JLabel jLabelBuzzer;
    private javax.swing.JLabel jLabelLight;
    private javax.swing.JLabel jLabelMainBoard;
    private javax.swing.JLabel jLabelNoise;
    private javax.swing.JLabel jLabelRGB;
    private javax.swing.JLabel jLabelServo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    //Hongjie: additional var.
    public Vector vecFrameProperty;
    public Vector vecDeviceProperty;
    public myUtils utils;

    //const
    public final int iFrameNum = 10;
}
